#! /usr/bin/env node

const program = require('commander');
const inquirer = require('inquirer');
const chalk = require('chalk');
const fs = require('fs');
const os = require('os');
const path = require('path');
const shell = require("shelljs");
const fse = require('fs-extra');
const openExplorer = require('open-file-explorer');

var initPath = "";

program
    .command('check')
    .alias('c')
    .description('check the current version')
    .action(option => {
        console.log(printItalicBold('cilv v0.2.0'));
        if (shell.exec('concurrently -v').code == 1) {
            console.log('Missing global dependency detected... ❌');
            console.log('Pre-installing...');
            console.log(chalk.default.bold('Fetching `Concurrently` library from npm...📦'));
            console.log(shell.exec('npm install concurrently -g').stdout);
        } else {
            console.log('No Missing Dependency. ✅');
        }
    });

program
    .command('init')
    .alias('i')
    .description('init file')
    .action(option => {
        let config = {
            fileName: null
        };
        // console.log(chalk.default.bold('cilv v0.0.1'));

        if (process.argv[3]) {
            prepareILV(process.argv[3]);
        } else {
            let promps = [];
            if (config.fileName === null) {
                promps.push({
                    type: 'input',
                    name: 'fileName',
                    message: 'Please input the ilv file name',
                    validate: input => {
                        if (!input) {
                            return 'The file name can\'t be empty';
                        }
                        config.fileName = input;
                        return true;
                    }
                });
            }

            inquirer.prompt(promps).then(async (answers) => {
                prepareILV();
            });
        }
        function prepareILV(fileName) {
            let template = fs.readFileSync(path.resolve(__dirname + '/template.ilv'), 'utf-8')
                .replace("USERPLACEHOLDER", os.userInfo().username);

            fs.writeFile(`${process.cwd()}\\${fileName}.ilv`, template, 'utf8', function (error) {
                if (error) {
                    console.log(error);
                    return false;
                } else {
                    console.log(chalk.bold(fileName + '.ilv document is successfully created.'));
                }
            });
        }
    });

program
    .command('deploy')
    .alias('d')
    .description('listen ilv')
    .action(option => {
        let config = {
            fileName: null
        };
        // console.log(chalk.default.bold('cilv v0.0.1'));

        if (process.argv[3]) {
            parseILV(process.argv[3]).then((res) => {
                if (res) {
                    startILV(process.argv[3]);
                }
            });
        } else {
            let promps = [];
            if (config.fileName === null) {
                promps.push({
                    type: 'input',
                    name: 'fileName',
                    message: 'Please input the ilv file name',
                    validate: input => {
                        if (!input) {
                            return 'The file name can\'t be empty';
                        }
                        config.fileName = input;
                        return true;
                    }
                });
            }

            inquirer.prompt(promps).then(async (answers) => {
                console.log(answers);
                if (answers.fileName) {
                    parseILV(answers.fileName).then((res) => {
                        if (res) {
                            startILV(answers.fileName);
                        }
                    });
                }
            });
        }
    });

program
    .command('build')
    .alias('b')
    .description('build ilv')
    .action(option => {
        let config = {
            fileName: null
        };
        // console.log(chalk.default.bold('cilv v0.0.1'));

        if (process.argv[3]) {
            parseILV(process.argv[3]).then((res) => {
                if (res) {
                    // startILV(process.argv[3]);
                    buildILV();
                }
            });
        } else {
            let promps = [];
            if (config.fileName === null) {
                promps.push({
                    type: 'input',
                    name: 'fileName',
                    message: 'Please input the ilv file name',
                    validate: input => {
                        if (!input) {
                            return 'The file name can\'t be empty';
                        }
                        config.fileName = input;
                        return true;
                    }
                });
            }

            inquirer.prompt(promps).then(async (answers) => {
                console.log(answers);
                if (answers.fileName) {
                    parseILV(answers.fileName).then((res) => {
                        if (res) {
                            // startILV(answers.fileName);
                            buildILV();
                        }
                    });
                }
            });
        }
    });

program.parse(process.argv);

function parseILV(fileName) {
    initPath = process.cwd();
    console.log(`${process.cwd()}\\${fileName}.ilv`);
    return new Promise((resolve, reject) => {

        fs.stat(`${process.cwd()}\\${fileName}.ilv`, function (err, stat) {
            if (err == null && stat) {
                // console.log('File exists');
                // console.log(stat);
                // fs.writeFileSync(path.resolve(__dirname, '../parser/' + `${fileName}.ilv`), fs.readFileSync(`${process.cwd()}\\${fileName}.ilv`));
                let package = {
                    "name": "@netbeifeng/ilv-interactive-video-authoring-tool",
                    "version": "0.2.0",
                    "private": false,
                    "bin": {
                        "cilv": "./cli/cilv"
                    },
                    "dependencies": {
                        "@babel/core": "7.12.3",
                        "@pmmmwh/react-refresh-webpack-plugin": "0.4.3",
                        "@svgr/webpack": "5.5.0",
                        "@testing-library/jest-dom": "^5.11.9",
                        "@testing-library/react": "^11.2.5",
                        "@testing-library/user-event": "^12.6.3",
                        "@traptitech/markdown-it-katex": "^3.4.3",
                        "@types/three": "^0.125.3",
                        "@typescript-eslint/eslint-plugin": "^4.5.0",
                        "@typescript-eslint/parser": "^4.5.0",
                        "axios": "^0.21.1",
                        "babel-eslint": "^10.1.0",
                        "babel-jest": "^26.6.0",
                        "babel-loader": "8.1.0",
                        "babel-plugin-named-asset-import": "^0.3.7",
                        "babel-preset-react-app": "^10.0.0",
                        "bfj": "^7.0.2",
                        "camelcase": "^6.1.0",
                        "case-sensitive-paths-webpack-plugin": "2.3.0",
                        "chalk": "^2.4.2",
                        "commander": "^2.20.0",
                        "concurrently": "^6.2.0",
                        "css-loader": "4.3.0",
                        "dotenv": "8.2.0",
                        "dotenv-expand": "5.1.0",
                        "eslint": "^7.11.0",
                        "eslint-config-react-app": "^6.0.0",
                        "eslint-plugin-flowtype": "^5.2.0",
                        "eslint-plugin-import": "^2.22.1",
                        "eslint-plugin-jest": "^24.1.0",
                        "eslint-plugin-jsx-a11y": "^6.3.1",
                        "eslint-plugin-react": "^7.21.5",
                        "eslint-plugin-react-hooks": "^4.2.0",
                        "eslint-plugin-testing-library": "^3.9.2",
                        "eslint-webpack-plugin": "^2.1.0",
                        "file-loader": "6.1.1",
                        "fs-extra": "^9.0.1",
                        "github-markdown-css": "^4.0.0",
                        "gsap": "^3.6.0",
                        "highlight.js": "^10.6.0",
                        "howler": "^2.2.1",
                        "html-minifier": "^4.0.0",
                        "html-webpack-plugin": "4.5.0",
                        "identity-obj-proxy": "3.0.0",
                        "inquirer": "^6.3.1",
                        "jest": "26.6.0",
                        "jest-circus": "26.6.0",
                        "jest-resolve": "26.6.0",
                        "jest-watch-typeahead": "0.6.1",
                        "js-beautify": "^1.13.5",
                        "markdown-it": "^12.0.6",
                        "markdown-it-color": "^2.1.1",
                        "markdown-it-highlightjs": "^3.4.0",
                        "markdown-it-link-target": "^1.0.2",
                        "markdown-it-task-lists": "^2.1.1",
                        "mini-css-extract-plugin": "0.11.3",
                        "node-sass": "^5.0.0",
                        "node-webvtt": "^1.9.3",
                        "npm": "^7.11.1",
                        "open-file-explorer": "^1.0.2",
                        "optimize-css-assets-webpack-plugin": "5.0.4",
                        "pegjs": "^0.10.0",
                        "pegjs-util": "^1.4.21",
                        "pnp-webpack-plugin": "1.6.4",
                        "postcss-flexbugs-fixes": "4.2.1",
                        "postcss-loader": "3.0.0",
                        "postcss-normalize": "8.0.1",
                        "postcss-preset-env": "6.7.0",
                        "postcss-safe-parser": "5.0.2",
                        "prompts": "2.4.0",
                        "react": "^17.0.1",
                        "react-app-polyfill": "^2.0.0",
                        "react-dev-utils": "^11.0.2",
                        "react-dom": "^17.0.1",
                        "react-draggable": "^4.4.3",
                        "react-helmet": "^6.1.0",
                        "react-refresh": "^0.8.3",
                        "resolve": "1.18.1",
                        "resolve-url-loader": "^3.1.2",
                        "sass-loader": "^10.0.5",
                        "semver": "7.3.2",
                        "shelljs": "^0.8.3",
                        "style-loader": "1.3.0",
                        "terser-webpack-plugin": "4.2.3",
                        "ts-pnp": "1.2.0",
                        "typescript": "^4.1.3",
                        "url-loader": "4.1.1",
                        "web-vitals": "^1.1.0",
                        "webpack": "4.44.2",
                        "webpack-dev-server": "3.11.0",
                        "webpack-manifest-plugin": "2.2.0",
                        "workbox-webpack-plugin": "5.1.4"
                    },
                    "scripts": {
                        "start": "npm run launch",
                        "deploy": "npm run parse && npm run launch",
                        "launch": "node scripts/start.js",
                        "parse": "node parser/parser.js " + fileName + " " + initPath,
                        "listen": "node parser/listener.js " + fileName,
                        "build": "node scripts/build.js",
                        "test": "node scripts/test.js"
                    },
                    "eslintConfig": {
                        "extends": [
                            "react-app",
                            "react-app/jest"
                        ]
                    },
                    "browserslist": {
                        "production": [
                            ">0.2%",
                            "not dead",
                            "not op_mini all"
                        ],
                        "development": [
                            "last 1 chrome version",
                            "last 1 firefox version",
                            "last 1 safari version"
                        ]
                    },
                    "devDependencies": {
                    },
                    "jest": {
                        "roots": [
                            "<rootDir>/src"
                        ],
                        "collectCoverageFrom": [
                            "src/**/*.{js,jsx,ts,tsx}",
                            "!src/**/*.d.ts"
                        ],
                        "setupFiles": [
                            "react-app-polyfill/jsdom"
                        ],
                        "setupFilesAfterEnv": [
                            "<rootDir>/src/setupTests.js"
                        ],
                        "testMatch": [
                            "<rootDir>/src/**/__tests__/**/*.{js,jsx,ts,tsx}",
                            "<rootDir>/src/**/*.{spec,test}.{js,jsx,ts,tsx}"
                        ],
                        "testEnvironment": "jsdom",
                        "testRunner": "C:\\Users\\Chang\\Desktop\\SS21\\BA\\bachelor-arbeit\\node_modules\\jest-circus\\runner.js",
                        "transform": {
                            "^.+\\.(js|jsx|mjs|cjs|ts|tsx)$": "<rootDir>/config/jest/babelTransform.js",
                            "^.+\\.css$": "<rootDir>/config/jest/cssTransform.js",
                            "^(?!.*\\.(js|jsx|mjs|cjs|ts|tsx|css|json)$)": "<rootDir>/config/jest/fileTransform.js"
                        },
                        "transformIgnorePatterns": [
                            "[/\\\\]node_modules[/\\\\].+\\.(js|jsx|mjs|cjs|ts|tsx)$",
                            "^.+\\.module\\.(css|sass|scss)$"
                        ],
                        "modulePaths": [],
                        "moduleNameMapper": {
                            "^react-native$": "react-native-web",
                            "^.+\\.module\\.(css|sass|scss)$": "identity-obj-proxy"
                        },
                        "moduleFileExtensions": [
                            "web.js",
                            "js",
                            "web.ts",
                            "ts",
                            "web.tsx",
                            "tsx",
                            "json",
                            "web.jsx",
                            "jsx",
                            "node"
                        ],
                        "watchPlugins": [
                            "jest-watch-typeahead/filename",
                            "jest-watch-typeahead/testname"
                        ],
                        "resetMocks": true
                    },
                    "babel": {
                        "presets": [
                            "react-app"
                        ]
                    }
                }

                fs.writeFileSync(path.resolve(__dirname, '../package.json'), JSON.stringify(package), (err) => {
                    if (err) {
                        console.log(err);
                        reject(false);
                    }
                });
                console.log(printItalicBold("Parsing..."));
                shell.cd(path.resolve(__dirname, '../'));
                console.log(shell.exec('npm run parse').stdout);
                console.log(chalk.default.blueBright(`${fileName}.ilv is sucessful parsed.`));
                // return Promise()
                resolve(true);
            } else {
                console.log('Some other error: ', err.code);
                reject(false);
            }
        });
    });
}

function buildILV() {
    const srcDir = path.resolve(__dirname, '../build');
    const destDir = path.resolve(initPath, './build');
    console.log(printItalicBold("Building..."));
    shell.cd(path.resolve(__dirname, '../'));

    if (shell.exec('npm run build').code == 0) {
        console.log(chalk.default.greenBright("Build Success!"));
        console.log(printItalicBold("Copying..."));
        console.log(chalk.default.redBright('From: '), srcDir, chalk.default.redBright('To: '), destDir);
        fse.copySync(srcDir, destDir, { overwrite: true }, function (err) {
            if (err) {
                console.error(err);
            }
        });

        openExplorer(destDir);
    } else {
        console.log(chalk.default.redBright("Build Fail!"));
    }
}

function startILV(fileName) {
    console.log(printItalicBold("Starting..."));
    shell.cd(path.resolve(__dirname, '../'));
    console.log(shell.exec(`concurrently \"npm run launch\" \"node parser/listener.js ${path.resolve(initPath + '/' + fileName + '.ilv')} ${fileName}\"`).stdout);
}

function printItalicBold(str) {
    return chalk.default.italic(chalk.default.bold(str));
}